name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Análisis estático de código (opcional)
      # Si no necesitas ESLint, puedes comentar o eliminar el siguiente paso
      # - name: Run static code analysis
      #   run: |
      #     echo "Skipping npm install as no package.json is present."
      #     npx eslint .
