name: CI for Web Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-html:
    name: Validate HTML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate HTML
        uses: Cyb3r-Jak3/html-validator-action@v1
        with:
          path: "./" # Carpeta donde están tus archivos HTML
