name: CI for Web Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-html:
    name: Validate HTML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate HTML
        uses: marc1706/validate-html-action@v1.0.0
        with:
          directory: "./" # Cambia esto si tus archivos HTML están en otra carpeta
