name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Configura el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instala Node.js (si es necesario para tus pruebas)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instala dependencias
      - name: Install dependencies
        run: npm install

      # 4. Ejecuta las pruebas
      - name: Run tests
        run: npm test

      # 5. Análisis estático de código
      - name: Run static code analysis
        run: |
          npx eslint .  # Sustituye por SonarQube si lo usas
