name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_analyze:
    name: Run Tests and SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - uses: actions/checkout@v4

      # Ejecutar el análisis en un contenedor Docker
      - name: Run SonarQube in Docker
        run: |
          docker run \
          -e SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }} \
          -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
          -v ${{ github.workspace }}:/usr/src \
          sonarsource/sonar-scanner-cli:latest \
          sonar-scanner -Dsonar.projectKey=PruebaCalidad2 -Dsonar.sources=.
